{{- if not .Values.provisioning.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "excalibase-auth.fullname" . }}
  labels:
    {{- include "excalibase-auth.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.provisioning.existingSecretPatKey }}: {{ .Values.provisioning.pat | quote }}
{{- end }}
